### ISSUE TITLE
Refactor to use React-Router

### ISSUE THREAD

**Issue by mattxwang** [uclaacm/cipher-salad#24]
At minimum, we'll need several routes for the main story, the shareable cipher creation, shareable cipher playing, etc. We'll need to encode some data in the route, and then pull it out to figure out what the cipher should be.

I'd like to (if possible) refactor the sections to also have different routes as well. Should make it easier for kids to navigate, as well as for instructors to link to certain things.

**Comment by krashanoff** [comment]
Currently tackling this on `share-cipher`. Still need to deal with the design of the sharable ciphers page but the core is there.
