### ISSUE TITLE
Accessibility Pass-through

### ISSUE THREAD

**Issue by mattxwang** [uclaacm/cipher-salad#35]
Some quick notes:

- [x] change all non-clickable elements to not use buttons anymore - causes issues w/ tabbing through page
- [x] believe we need to change `role` or `tabindex` on floating scrollspy nav
- [x] alt text for images, icons
- [x] audit hover functionality to be keyboard-usable
- [x] not sure how animations and staggered content work for screenreaders, should investigate further
- [x] is it possible to make the wheel accessible at all? Maybe adding buttons or something?
- [x] rephrase copy & CTAs to be clearer (e.g. instead of a button that says "Go", button says "Play the Game" or something)

**Comment by krashanoff** [comment]
I'll cover this tonight. The biggest problem for me is the tab order and markup. Wheel could be made accessible with buttons like you said. Animations I think are okay with screenreaders as long as the element is still drawn to the document on load.
